---
title: "Schedule"
---

| Week | Tutorial                         | Prerequisites |
|------|----------------------------------|---------------|
| 09   | [Introduction](tutorials/introduction.qmd) | ---           |
|      | **Exploring archaeological data**                |
| 10   | [Exploring data with R](tutorials/eda_with_r.qmd)       | [{{< fa link >}}Evergreen notes](https://notes.andymatuschak.org/Evergreen_notes)<br>[Install R](https://cran.r-project.org/) on your computer |
| 11   | [Visualising distributions](tutorials/visualising_distributions.qmd)        | [{{< fa video >}}  The Role of Visualization in Exploratory Data Analysis](https://www.youtube.com/watch?v=ZdPNBF6GWBw)           |
| 12   | [Visualising relationships](tutorials/visualising_relationships.qmd)        | [{{< fa book >}} *The Visual Display of Quantitative Information*](https://archive.org/details/the-visual-display-of-quantitative-information-2ed-by-tufte-edward-r.-z-lib.org), ch. 4, 5 & 6 |
| 13   | [Summary statistics](tutorials/summary_statistics.qmd)               | {{< fa book >}} *Quantifying Archaeology*, [ch. 4](https://doi.org/10.1515/9781474472555-005)            |
|      | **Working with archaeological data**             |
| 14   | [Importing and transforming data](tutorials/tidy_data.qmd)  | [{{< fa book >}} Data Organization in Spreadsheets](https://doi.org/10.1080/00031305.2017.1375989) |
| 15   | *Spring vacation*                | ---           |
| 16   | [Data analysis workflows](tutorials/workflows.qmd)          | [{{< fa book >}} Computational Reproducibility in Archaeological Research: Basic Principles and a Case Study of Their Implementation](https://doi.org/10.1007/s10816-015-9272-9)           |
| 17   | [Replication Workshop I](tutorials/replication.qmd)           | [{{< fa book >}} When the World’s Population Took Off](https://doi.org/10.1126/science.1208880)<br />[{{< fa book >}} One paper to be replicated](tutorials/replication.qmd#prerequisites)            |
| 18   | [Replication Workshop II](tutorials/replication.qmd)          | ---           |
|      | **Modelling archaeological data**                |
| 19   | Hypothesis testing               | ---           |
| 20   | Regression                       | ---           |
| 21*  | Multivariate analysis            | ---           |
| 22   | Review & course evaluation       | ---           |

\* Substitute instructor
